---
language: csharp
solution: PowerShell.sln
mono: none

git:
  depth: 1

stages:
  # - sanity testing
  - build
  # - acceptance testing

jobs:
  include:
    - stage: build
      dotnet: "2.1.300"
      script:
        - dotnet build

matrix:
  fast_finish: true
  allow_failures:
  - stage: sanity testing
  - script: make sanity
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8.1

# travis-ci will quit using the cache if an enviroment variable changes.
# CACHE_VERSION is not used for anything other than invalidating the cache.
# DOTNET_SKIP_FIRST_TIME_EXPERIENCE is to skip the dotnet-cli initialization,
# which is expensive and unneeded for build agents.
env:
  global:
    - CACHE_VERSION=netcoreapp.2.1-sdk.2.1.300
    - POWERSHELL_TELEMETRY_OPTOUT=1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1

cache:
  timeout: 360
  directories:
    - $HOME/.nuget
    - deps
