version: 0.1

jobs:
  build:
    machine:
      enabled: true
    working_directory: ~/project/Powershell
    steps:
      - run:
          command: git clone http://github.com/nutanix/Powershell
      - run:
          command: wget -q https://packages.microsoft.com/config/ubuntu/14.04/packages-microsoft-prod.deb
      - run:
          command: sudo dpkg -i packages-microsoft-prod.deb
      - run:
          command: sudo apt-get install apt-transport-https
      - run:
          command: sudo apt-get update
      - run:
          command: sudo apt-get install dotnet-sdk-2.1
      - run:
          command: cd Powershell && dotnet build
